### PR TITLE
V5 API upgrade

### PR DESCRIPTION
**Pull request by palfrey**
This upgrades the API usage to use the v5 REST API (as detailed at https://www.pivotaltracker.com/help/api/rest/v5). I haven't added in any of the new bits (e.g. activity data), but I've just ported over the existing bits so that we can now later add in the new bits.

Note that
* XML stuff has been replaced with JSON throughout, as the new API doesn't seem to support XML any more
* Authentication via username/password has gone away, in favour of API tokens which are only findable via the Pivotal profile.

### CODE REVIEW

**Comment by mcintyre321** [comment]
Will this ever be merged and pushed to github?

**Comment by kajalp** [comment]
Can this be merged?

**Comment by kajalp** [comment]
@AlexCuse @bhameyie can you please merge this?

**Comment by AlexCuse** [comment]
Sorry about this, have not been getting notifications on this repository. 

I am at a different job now and no longer using pivotal, but can take a look this weekend.

**Comment by kajalp** [comment]
That would be awesome. Thank you!

**Comment by kajalp** [comment]
Thank you!

**Comment by AlexCuse** [comment]
Sorry for the delay this is merged.  Hope it works :)

I will try to publish to nuget soon.  Let me know if you're still actively using it and I can give direct commit access to this repository.

**Comment by kajalp** [comment]
I am! That would be great! Thanks Alex!

Sincerely,

Kajal Parekh

**Comment by AlexCuse** [comment]
Awesome - I will give you direct commit rights so I don't screw you guys over in the future.

You can get my email from the git logs - get in touch and I will set you up for NuGet publishing as well.

**Pull request merged**
